image_source="/home/$USER/.config/neofetch/logo.txt"

shell_path="on"
shell_version="off"
separator=" "
gap=-4

print_info(){
    info "\e[31m" users
    #info "\e[32m" kernel
    info "\e[95m" uptime
    info "\e[96m" wm
    info "\e[32m" shell
    info "\e[34m" packages
    info "\e[33m" memory
    #info "\e[33m" cpu
    #info "\e[33m" gpu
    prin "\033[1;31m⬤ \n \n \033[1;32m⬤ \n \n \033[1;33m⬤ \n \n \033[1;34m⬤ \n \n \033[1;35m⬤ \n \n \033[1;36m⬤ \n \n \033[1;37m⬤"
}