#!/usr/bin/bash

read_lines(){
    while read line; do
        if [[ $line == *"="* && $line != \#* ]]; then
            export $line
        fi
    done </home/iniridwanul/Ifritgram/.env
    echo -e "Variables Exported"
}

ifritgram_run(){
    if [ -d "/home/iniridwanul/Ifritgram/venv" ]; then
        echo -e "Virtual Environment Found"
        source /home/iniridwanul/Ifritgram/venv/bin/activate
        echo -e "Virtual Environment Activated"
        if [ -f "/home/iniridwanul/Ifritgram/.env" ]; then
            echo -e ".env File Found"
            read_lines
            python3 /home/iniridwanul/Ifritgram/ifritgram
        else
            echo -e ".env File Not Found"
        fi
    else
        echo -e "Virtual Environment Not Found"
    fi
}

ifritgram_run