#!/bin/bash

# Author: iniridwanul
# Email Address: iniridwanul@gmail.com

# The following command fetches the latest mirrorlist from the Arch Linux website
curl -s "https://archlinux.org/mirrorlist/?country=all&protocol=http&protocol=https&ip_version=4&use_mirror_status=on" | \
    # The 'sed' command is used to uncomment the lines starting with '#Server' to activate the server list
    sed '0,/^#Server/ s/^#//' | 
    # The 'tee' command writes the modified mirrorlist to the /etc/pacman.d/mirrorlist file with elevated privileges
    sudo tee /etc/pacman.d/mirrorlist > /dev/null  

# Prints a success message indicating the mirror list has been updated
echo -e "Mirrorlist updated successfully!"

# The following command synchronizes the package databases and upgrades the system packages
sudo pacman -Syu